### ISSUE TITLE
Area graphics leave artifacts on the map after cancelling

### ISSUE THREAD

**Issue by rlee-rii** [missioncommand/emp3-android#303] opened 2017-10-17 15:00 UTC
1. Plot two points of an area graphic (any graphic that requires a min of 3 points).
2. Instead of clicking to plot the third point, drag the green dot to place the third point.
3. Drag another green dot to create a fourth point.
4. Delete one of the original 2 plotted points by double clicking on it.
5. Cancel the graphic. A blue "drag" dot remains. Sometimes, a green dot also remains on the map.

**Comment by rsupnekar** [comment] 2017-10-20 17:24
The issue was traced to a problem with control points. When a polygon is completed for the first time by dragging a green dot, the green dot turns blue, but the original green dot is not restored.  When the graphic is canceled, the dot count is incorrect and throws an exception during cleanup.

**Comment by rsupnekar** [comment] 2017-10-20 17:32
The issue is fixed in 3.0.2-SNAPSHOT found in the link below.  There are multiple snapshots with the same version number, so always use the latest by date and time.

https://oss.jfrog.org/artifactory/libs-snapshot/mil/army/missioncommand/

**Closed as completed** 2017-10-20 17:34 UTC
